# Generated by Django 4.2 on 2023-04-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default_profile.jpg", upload_to="profile_pics"
            ),
        ),
    ]
