# Generated by Django 4.2 on 2023-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ring_alarm",
            field=models.BooleanField(default=True),
        ),
    ]
