# Generated by Django 4.2 on 2023-04-22 09:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photo_upload", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_name",
                    models.TextField(verbose_name=django.contrib.auth.models.User),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_target.jpg", upload_to="target_pics"
                    ),
                ),
                ("call_police", models.BooleanField(default=True)),
                ("ring_alarm", models.BooleanField(default=True)),
                ("message_contacts", models.BooleanField(default=True)),
                ("message_to_contacts", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Photo",),
    ]
