# Generated by Django 4.2 on 2023-04-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_upload", "0002_target_delete_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="message_to_contacts",
            field=models.TextField(blank=True),
        ),
    ]
