# Generated by Django 4.2 on 2023-04-23 01:30

from django.db import migrations, models
import photo_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_upload", "0003_alter_target_message_to_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=photo_upload.models.get_upload_path
            ),
        ),
    ]
