# Generated by Django 4.2 on 2023-04-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo_upload", "0004_alter_target_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="target",
            old_name="message_to_contacts",
            new_name="message_to_owner",
        ),
        migrations.RemoveField(model_name="target", name="call_police",),
        migrations.RemoveField(model_name="target", name="message_contacts",),
        migrations.RemoveField(model_name="target", name="ring_alarm",),
    ]
